[[module]]
module = "modules/fileserver.gr.wasm"
route = "/static/..."
volumes = {"/" = "static/"}

[[module]]
module = "target/wasm32-wasi/release/bartholomew.wasm"
route = "/..."
volumes = { "content/" = "content/" , "templates/" = "templates/", "shortcodes/" = "shortcodes/", "scripts/" = "scripts/", "config/" = "config/"}
